[package]
name = "tablefy"
description = "An easy way to display any struct as a table!"
version = "0.1.3"
license = "MPL-2.0"
repository = "https://github.com/Calmynt/Tablefy"
readme = "README.md"
keywords = ["table", "format", "serialize", "struct", "derive"]
categories = ["command-line-interface"]
authors = ["ENBYSS"]
edition = "2018"
maintenance = { status = "actively-developed" }

[dependencies]
prettytable = "0.10.0"
# tablefy_derive = "0.2.1"
# tablefy_derive = {path = "tablefy_derive"}
